%YAML 1.0
---

Dataset:
  type: "euroc"
  path: "datasets/euroc/mh02"
  start_idx: 800

Log:
  path: "/mnt/i/project/slam/tmp/test/log/"
  enable_std: true
  
Visualizer:
  enable: false
  port: 8733

Calibration:
  path: "configs/eruco/calibration.yaml"

Network:
  droid:
    fnet_path: "checkpoints/droid_fnet.pt"
    cnet_path: "checkpoints/droid_cnet.pt"
    update_path: "checkpoints/droid_update.pt"
  superpoint:
    net_path: "checkpoints/superpoint.pt"
    max_num_keypoints: 512

Tracking:
  motion_filter_thresh: 2.5
  motion_model: "constant_velocity" # fixed, constant_velocity, imu, constant_acceleration(not supported)

LocalMapping:
  multi_thread: true

Initialization:
  thresh: 0.5

GlobalMapping:
  thresh: 0.5

############################################################# OLD CONFIGS

Frontend:  
  use_segmentation: false
  use_depth_estimation: false
  use_tracking: false
  only_plot_image: false
  plot_matches: false
  publish_debug: true

SlideWindow:
  window_size: 10
  init_window_size: 10
  publish_matches: true
  publish_pred_pcd: false
  publish_sparse_pcd: true
  publish_debug: true

Backend:
  viz_enalbe: true
  port_num: 4567
  Training:
    init_itr_num: 1050
    init_gaussian_update: 100
    init_gaussian_reset: 500
    init_gaussian_th: 0.005
    init_gaussian_extent: 30
    tracking_itr_num: 100
    mapping_itr_num: 150
    gaussian_update_every: 150
    gaussian_update_offset: 50
    gaussian_th: 0.7
    gaussian_extent: 1.0
    gaussian_reset: 2001
    size_threshold: 20
    kf_interval: 5
    window_size: 8
    pose_window: 3
    edge_threshold: 1.1
    rgb_boundary_threshold: 0.01

    kf_translation: 0.08
    kf_min_translation: 0.05
    kf_overlap: 0.9
    kf_cutoff: 0.3
    prune_mode: 'slam'
    single_thread: False
    spherical_harmonics: False

    lr:
      cam_rot_delta: 0.003
      cam_trans_delta: 0.001

  opt_params:
    iterations: 30000
    position_lr_init: 0.0016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002

  model_params:
    sh_degree: 0
    source_path: ""
    model_path: ""
    resolution: -1
    white_background: False
    data_device: "cuda"

  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False

  Dataset:
    type: 'euroc'
    sensor_type: 'stereo'
    pcd_downsample: 128
    pcd_downsample_init: 32
    adaptive_pointsize: False
    point_size: 0.1
